name: Release Build

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community' # See 'Options' for all available distributions
      - name: Record versions
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version
          echo "version=$(git describe --abbrev=0 --tags)" > src/main/resources/appversion.properties
          echo "cat src/main/resources/appversion.properties"
          cat src/main/resources/appversion.properties
      - name: Build using Gradle shadowJar plugin # https://graalvm.github.io/native-build-tools/latest/gradle-plugin.html
        run: ./gradlew nativeCompile
      - name: Upload build to Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/native/nativeCompile/http4k-api