name: GraalVM build

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4.2.2
        with:
          distribution: temurin
          java-version: 21
      - name: Log versions
        run: |
          echo "JAVA_HOME: $JAVA_HOME"
          java -version
      - name: Build using Gradle shadowJar plugin # https://graalvm.github.io/native-build-tools/latest/gradle-plugin.html
        run: ./gradlew clean shadowJar
      - name: Upload build to Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/libs/http4k-api.jar